### ISSUE TITLE
Initial setting for the development

### ISSUE THREAD

**Issue by Aqrare** [HackerSamuraiDAO/2022-one-two-web3-hackathon-submission#3]

**Comment by taijusanagi** [comment]
Let’s have a habit to write descriptions when creating issues!

OK, I take this.
I'm creating the Chocomint new repo, and we can use it for this.

**Comment by taijusanagi** [comment]
But I think this app is a very simple one, so you can just create it from this template. 
https://github.com/HackerSamuraiDAO/template
